name: Bug Report
description: Report an issue with Squishy
title: ""
labels: ["Bug"]
body:
  - type: markdown
    attributes:
      value: |
        Have you found an issue with Squishy or one of it's components?

        Thanks for letting us know, please submit details of the bug below.

  - type: dropdown
    id: subsystem
    attributes:
      label: Which part of Squishy shows this problem
      options:
        - CLI
        - Gateware Library
        - Python Library
        - Applet
      multiple: true
    validations:
      required: true

  - type: textarea
    id: bug-desc
    attributes:
      label: What happened?
      description: A clear and detailed report as possible
    validations:
      required: true

  - type: textarea
    id: bug-repro
    attributes:
      label: Reproduction Steps
      description: A clear and concise set of steps that are able to reproduce the bug
    validations:
      required: true

  - type: textarea
    id: bug-detail
    attributes:
      label: List any relevant additional details below if possible

  - type: dropdown
    id: os
    attributes:
      label: On which OS did this happen?
      options:
        - Linux
        - BSD
        - macOS
        - Windows
      multiple: true
    validations:
      required: true

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/squishy-scsi/squishy/blob/main/CODE_OF_CONDUCT.md)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
