name: "Squishy Tests"
on:
  push:
    paths:
      - '.github/workflows/tests.yml'
      - 'squishy/**'
      - 'tests/**'
      - 'noxfile.py'

jobs:
  test:
    runs-on: ubuntu-latest
    name: 'Test Squishy (Python ${{ matrix.python-version }})'
    strategy:
      matrix:
        python-version: ['3.11', '3.12', '3.13', '3.14.0-alpha.1']
    steps:
      - name: 'Setup Python'
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: 'Initialize Environment'
        shell: bash
        env:
          WORKSPACE: ${{ github.workspace }}
        run: |
          echo "$HOME/.local/bin:$PATH" >> $GITHUB_PATH
          echo "GITHUB_WORKSPACE=\"`pwd`\"" >> $GITHUB_ENV
          echo "TORII_TEST_INHIBIT_VCD=1" >> $GITHUB_ENV

      - name: 'Checkout'
        uses: actions/checkout@v4
        with:
          lfs: true
          submodules: true

      - name: 'Setup OSS CAD Suite'
        uses: YosysHQ/setup-oss-cad-suite@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: 'Setup'
        shell: bash
        run: |
          python -m pip install --user --upgrade pip setuptools wheel setuptools_scm nox

      - name: 'Run Tests'
        shell: bash
        timeout-minutes: 15 # Python 3.12 and 3.13 seem to just hang on testing ~sometimes~
        continue-on-error: ${{ matrix.python-version == '3.12' || matrix.python-version == '3.13' }}
        run: |
          nox -s test -- --coverage

      - name: 'Codecov Upload'
        uses: codecov/codecov-action@v4
        if: success() && github.repository == 'squishy-scsi/squishy'
        continue-on-error: true # It's not super mission critical that the coverage upload fails
        with:
          verbose: true
          files: ./build/tests/coverage.xml
          token: ${{ secrets.CODECOV_TOKEN }}
